package com.example.ynumedical.appointment_activities;

import java.text.SimpleDateFormat;
import java.util.Date;


public class Appointment {
    /**
     * Appointment class that stores necessary information for each individual appointment
     *
     * @param patientID a string that stores the patientID generated by FirebaseAuth
     * @param doctorID a string that stories the doctorID generated by FirebaseAuth
     * @param startTime a date that stores start time of the appointment. All appointments are one hour.
     * @param appointmentID a string that combines date and time of appointment with doctorID to create a unique ID for the appointment
     */

    private String patientID;
    private String doctorID;
    private Date startTime;
    private String appointmentID;

    public Appointment (String doctorID, String patientID, Date startTime) {
        this.patientID = patientID;
        this.doctorID = doctorID;
        this.startTime = startTime;
        SimpleDateFormat st = new SimpleDateFormat("yyyy/MM/dd hh:mm");
        SimpleDateFormat et = new SimpleDateFormat("yyyy/MM/dd hh:mm");
        SimpleDateFormat test = new SimpleDateFormat("yyyyMMddhhmm");
        //this.appointmentID = (int)startTime.getTime();
        this.appointmentID = test.format(startTime)+doctorID;
    }

    public Appointment() { }


    @Override
    public String toString() {
        return "" + patientID + " has a appointment with Dr." + doctorID + " at " + startTime;
    }




    //========================== Necessary ===============================
    public String getPatientID() {
        return patientID;
    }

    public void setPatientName(String patientID) {
        this.patientID = patientID;
    }

    public void setDoctor(String doctorID) {
        this.doctorID = doctorID;
    }

    public String getDoctorID() {
        return doctorID;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setAppointmentID(String appointmentID){this.appointmentID = appointmentID;}

    public String getAppointmentID() {
        return appointmentID;
    }
    //========================== Necessary ===============================
}


